arch:
   - amd64
   - ppc64le
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - $HOME/.npm
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - 14
  - 13
  - 12
  - 11
  - 10
script: "./coverage.sh"
sudo: false
