arch:
  - amd64
  - arm64
  - ppc64le
language: node_js
node_js:
  - 16
  - 15
  - 14
  - 13
  - 12
script: "./coverage.sh"
jobs:
  exclude:
    # this specific combination is broken within Travis at present
    - arch: ppc64le
      node_js: 16
